d <- read_excel("/Users/kweisman/Documents/Research (Stanford)/Projects/Templeton Grant/DATA WRANGLING/templeton_qts/_from Nikki/SC_TAT_SPSS data.xlsx") %>%
  mutate_all(funs(trimws)) %>%
  filter(!is.na(country), !is.na(quad), !is.na(researcher)) %>%
  mutate(country = factor(country,
                          levels = c("US", "Ghana", "Thailand", 
                                     "China", "Vanuatu")),
         urban_rural = factor(case_when(
           grepl("URBAN", quad) ~ "urban",
           grepl("RURAL", quad) ~ "rural"),
           levels = c("urban", "rural")),
         charismatic_local = factor(case_when(
           grepl("NON- CHRISTIAN", quad) ~ "local",
           grepl("CHRISTIAN", quad) & !grepl("NON- ", quad) ~ "charismatic"),
           levels = c("charismatic", "local")),
         quad = paste(urban_rural, charismatic_local, sep = " "),
         researcher = factor(researcher,
                             levels = c("JBrahinsky", "VDzokoto", "Jdulin", 
                                        "Faulino", "Emng", "Rsmith")),
         subject_gender = factor(case_when(
           grepl("Female", subject_gender) ~ "Female",
           grepl("Male", subject_gender) ~ "Male",
           subject_gender == "Other" ~ "Other")),
         subject_age = as.numeric(subject_age),
         prayfreqmin = recode_factor(
           prayfreqmin,
           "1" = "0-15 min",
           "2" = "15-30 min",
           "3" = "30-60 min",
           "4" = ">60 min"),
         sleephabit = factor(case_when(
           sleephabit %in% c("Back", "Baksaed (Back)") ~ "Back",
           sleephabit %in% c("Belly mainly", "Chest", "Front", "Stomache", "Tummy") ~ "Stomach",
           sleephabit %in% c("Saed (Side)", "Side") ~ "Side",
           sleephabit %in% c("Back and anyhow", "Back when it happened, now side.", "Back when it happened, side now", "Back, side and front", "Both", "Both and front", "Both Ekyir na nkyÉ?n", "Both, sees more in dreams when on her back", "Side and front", "Side because used to be back when sleep oaralysis - notes bitg physical and spuritual benefits", "Sides and front", "Sleeps on all sides - back, front and side", "Tugeta (Both)", "Used to sleep on back now face down or side") ~ "Multiple",
           sleephabit %in% c("Back Ekyir", "Neither", "No (Neither)", "Side NkyÉ?n", "Upside down", "Whenever weird on back") ~ "Other",
           sleephabit %in% c("Didnt ask", "I dont know") ~ "Unknown"),
           levels = c("Back", "Stomach", "Side", "Multiple", 
                      "Other", "Unknown")),
         morequesmoreanswr = recode_factor(
           morequesmoreanswr,
           "1" = "More questions",
           "2" = "More answers",
           "1.5" = "Other"),
         growcomfresolvdoubt = recode_factor(
           growcomfresolvdoubt,
           "1" = "Grow comfortable",
           "0" = "Resolve doubt",
           "0.5" = "Other"),
         deepquesdefanswr = recode_factor(
           deepquesdefanswr,
           "1" = "Deeper questions",
           "0" = "Definite answers",
           "0.5" = "Other"),
         subject_job = gsub("Na$", "NA", subject_job),
         subject_job = gsub("N/a$", "NA", subject_job),
         subject_hs = factor(case_when(
           subject_hs %in% c("No", "No schooling", "No 2 years primary",
                             "No only 3y primary", "No Oho/ dabi") ~ "No",
           subject_hs %in% c("Yes", "Yes Nyew", "Year 9") ~ "Yes",
           subject_hs %in% c("à¹?à¸?à¹?") ~ "Unknown")),
         subject_school = factor(case_when(
           subject_school %in% c("No", "No Oho/ dabi") ~ "No",
           subject_school %in% c("Yes", "Yes Nyew", "1yr",
                                 "1year at Tangoa") ~ "Yes",
           subject_school %in% c("Vocational", "Technical") ~ "Tech/Voc",
           subject_school %in% c("Masonry apprenticeship",
                                 "Electrician apprenticeship",
                                 "Catering apprenticeship") ~ "Apprenticeship",
           subject_school %in% c("Other", "Workshops",
                                 "Went to mission school after high school", 
                                 "Some courses") ~ "Other",
           grepl("à¹?", subject_school) ~ "Unknown"),
           levels = c("No", "Apprenticeship", "Tech/Voc", "Yes", 
                      "Other", "Unknown"))) %>%
  mutate_at(vars(subject_hs, subject_school, specialrole, #communicatewgod,
                 praysilly, prayprepbody, prayprepmind, tongues, godviapeople,
                 godviascript, godviamind, godvoxstrong, godvoxaloud, 
                 godvoxaloud_outsidehead, godvoxaloud_withears, 
                 godvoxaloud_turnhead, godvoxaloud_waking, godcommpics, 
                 godviavisions, godviavisions_outsidehead, 
                 godviavisions_witheyes, godviavisions_waking, godviadreams, 
                 godguideviaknowing, godguideviasensations, godsenseplaceinbody,
                 godsenseplaceinbody_loc, godviabodyexperiences, godviatouch,
                 godviatouch_realtouch, godviatouch_waking, godviasmell,
                 godviasmell_realsmell, godviasmell_waking, godexpviaawe, 
                 godconfirm, neartangiblegod, presencenotgod, beingentbody, 
                 seehearnotgod, whitelight, trmblshakespirtpwr, rushofspiritpwr,
                 intenseemospiritpwr, timeslowpray, spiritbeingencounter, 
                 voxwhenalone, voxwhenalone_outsidehead, voxwhenalone_withears,
                 voxwhenalone_turnhead, voxwhenalone_waking, seethingscornereye,
                 seethingscornereye_outsidehead, unusualexphearing_judge,
                 unusualexpseeing_judge, unusualexptouch_judge, 
                 unusualexpgod_judge, unusualexpentity_judge, trueanswers_judge,
                 falseanswers_judge, godvoxmistaken, teaforgod_outcome), 
            funs(convert_yesno)) %>%
  mutate_at(vars(godvoxaloud_freq, godviavisions_freq, godviadreams_freq,
                 godviatouch_freq, godviasmell_freq, godexpviaawe_freq,
                 neartangiblegod_freq, presencenotgod_freq, presencedemon_freq,
                 beingentbody_freq, trmblshakespirtpwr_freq, 
                 rushofspiritpwr_freq, intenseemospiritpwr_freq, 
                 timeslowpray_freq, mindspiritexitbody_freq, 
                 sleepparalysis_freq, voxwhenalone_freq, 
                 seethingscornereye_freq),
            funs(convert_consistfreq)) %>%
  mutate(abs_score = as.numeric(abs_score),
         socialharmony = factor(socialharmony,
                                levels = c("0", "1", "0.5"),
                                labels = c("Express feelings directly",
                                           "Maintain social harmony",
                                           "Other")),
         happyface = factor(happyface,
                            levels = c("1", "0", "0.5"),
                            labels = c("Show your honest emotions", 
                                       "Happy face", "Other")),
         understandthoughts = factor(understandthoughts,
                                     levels = c("0", "1"),
                                     labels = c("Important to understand",
                                                "Waste of time")),
         sharingdangerous = factor(sharingdangerous,
                                   levels = c("0", "1", "2", "3"),
                                   labels = c("Never dangerous",
                                              "Rarely dangerous",
                                              "Often dangerous",
                                              "Very often dangerous"))) %>%
  mutate_at(vars(godvoxaloud_judge, godviavisions_judge, godviatouch_judge,
                 godviasmell_judge, neartangiblegod_judge, presencenotgod_judge,
                 presencedemon, presencedemon_judge, beingentbody_judge,
                 seehearnotgod_judge, whitelight_judge, mindspiritexitbody,
                 humanshapeshift, spiritbeingencounter_judge, sleepparalysis,
                 voxwhenalone_judge, seethingscornereye_judge, othergodnotreal,
                 selfunsuregodreal, goddoubt, goddoubtdisclose, 
                 doubtimpttogrowth),
            funs(convert_yesmaybeno)) %>%
  mutate_at(vars(godviapeople_freq, godviascript_freq, godviamind_freq,
                 godcommpics_freq, godguideviaknowing_freq, 
                 godguideviasensations_freq,
                 hurtwfeelings_anger, hurtwthoughts_anger, 
                 healtheffectbyproxy_anger, hurtviaspirit_anger, 
                 awarespirit_anger, healtheffectself_anger, stopemo_anger, 
                 removethoughts_anger, controlemo_anger, shouldcontrol_anger, 
                 trycontrol_anger, disclose_anger, helpwthoughts_caring, 
                 helpviaspirit_caring, awarespirit_caring, 
                 healtheffectself_caring, healtheffectbyproxy_caring, 
                 toomuch_caring, disclose_caring, hurtwfeelings_envy, 
                 hurtwthoughts_envy, healtheffectself_envy, hurtviaspirit_envy, 
                 awarespirit_envy, disclose_envy, thoughtsharmppldirectly, 
                 spiritsusethoughtsharm, controlface, talkabtfeelings, 
                 sharefeelingshere, witchcraft_judge, sharethought_judge, 
                 controlbody_judge, choochoo_imagine, teddydinner_imagine, 
                 invisiblefriend_imagine, childsplayopinion_imagine, 
                 adultsplaywchild_imagine, adultsscarekids_imagine, 
                 teaforgod_imagine, magicalthinking),
            funs(convert_often)) %>%
  mutate_at(vars(childexp_abs, forgetsurrounding_abs, poeticlanguage_abs,
                 starepicture_abs, mindenvelopworld_abs, cloudshapes_abs,
                 vividdaydream_abs, mysticalexp_abs, stepoutsidemyself_abs, 
                 textures_abs, doublyreal_abs, caughtupinmusic_abs, 
                 heavybody_abs, sensepresence_abs, woodfireimagine_abs, 
                 immersednature_abs, colormeaning_abs, wanderthoughtstask_abs,
                 clearpastexp_abs, meaninglesstoothers_abs, actinginplay_abs, 
                 visualthoughts_abs, delightsmallthings_abs, organmusic_abs, 
                 changenoise_abs, vividsmellmemories_abs, synesthesiasound_abs, 
                 predictwords_abs, physicalmemories_abs, fascinatingvoice_abs,
                 invisiblepresence_abs, sponthoughtsimages_abs, 
                 synesthesiasmell_abs, emosunset_abs), 
            funs(convert_truefalse)) %>%
  # MISSING:
  # mutate_at(vars(imaginationimportantkids_judge, 
  #                imaginationimportantadults_judge),
  #           funs(convert_often3)) %>%
  mutate_at(vars(adultsimagineimpossible_import, adultsimaginepossible_import),
            funs(convert_important)) %>%
  mutate_at(vars(specialmessage_scid, specialmessagenotgod_scid, 
                 threatening_scid, importantperson_scid, hypochondriasis_scid, 
                 somaticshift_scid, terribleact_scid, alienthought_scid #, 
                 # MISSING:
                 # thoughtstaken_scid, thoughtsbroadcast_scid, hearthings_scid, 
                 # hospitalhx_scid
                 ),
            funs(convert_present)) %>%
  mutate_at(vars(choochoo_encourage, teddydinner_encourage, 
                 invisiblefriend_encourage, adultsplaywchild_encourage, 
                 adultscarekids_encourage, teaforgod_encourage), 
            funs(convert_encourage))